import meatUrl from '@/assets/market/meatImg.png';
import squidUrl from '@/assets/market/squidImg.png';

export const products = [
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
];
export const productsDetail = [
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
    rank: '수산물 부문 1위',
    origin: '대한민국',
    review: 3281,
    isSave: true,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
    rank: '냉동식품 부문 2위',
    origin: '호주',
    review: 2503,
    isSave: false,
  },
  {
    id: 3,
    imgUrl: squidUrl,
    name: '통밀 또띠아 300g, 1개',
    price: 9450,
    discountRate: 5,
    discountPrice: 9000,
    rank: '가격 우수 식품',
    origin: '호주',
    review: 896,
    isSave: false,
  },
  {
    id: 4,
    imgUrl: meatUrl,
    name: '한끼 닭가슴살 150g, 3개',
    price: 9545,
    discountRate: 15,
    discountPrice: 8300,
    rank: '간편식품 부문 인기 상품',
    origin: '미국',
    review: 4306,
    isSave: true,
  },
];
export const timeSaleProduct = {
  id: 5,
  imgUrl: squidUrl,
  name: '참소스',
  price: 8125,
  discountRate: 25,
  discountPrice: 6500,
  targetDate: '2026-08-21T10:00:00',
};
export const saveRecipeProducts = [
  {
    id: 3,
    imgUrl: squidUrl,
    name: '통밀 또띠아 300g, 1개',
    price: 9450,
    discountRate: 5,
    discountPrice: 9000,
  },
  {
    id: 4,
    imgUrl: meatUrl,
    name: '한끼 닭가슴살 150g, 3개',
    price: 9545,
    discountRate: 15,
    discountPrice: 8300,
  },
  {
    id: 1,
    imgUrl: squidUrl,
    name: '통밀 또띠아 300g, 1개',
    price: 9450,
    discountRate: 5,
    discountPrice: 9000,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '한끼 닭가슴살 150g, 3개',
    price: 9545,
    discountRate: 15,
    discountPrice: 8300,
  },
];
export const recipes = [
  {
    imgUrl: meatUrl,
    name: '매콤 우삼겹 아끼소바',
  },
  {
    imgUrl: meatUrl,
    name: '우삼겹 부타동',
  },
  {
    imgUrl: meatUrl,
    name: '매콤 우삼겹 아끼소바',
  },
  {
    imgUrl: meatUrl,
    name: '우삼겹 부타동',
  },
];
