// 마이페이지 레시피·식단 — 저장/완료 레시피 더미
import foodImage from '../assets/feed/food.png';

export const DUMMY_RECIPES = [
  {
    id: 'r1',
    title: '양파 볶음밥',
    time: '30분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 3,
    image: foodImage,
    isSaved: true,
    isCompleted: true,
    completedDate: '8월 15일 완료',
    feedback: '쉬웠어요',
    ingredientCount: '사용한 재료 개수 8개',
  },
  {
    id: 'r2',
    title: '양파 가득 짜장면',
    time: '30분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 3,
    image: foodImage,
    isSaved: true,
    isCompleted: true,
    completedDate: '8월 15일 완료',
    feedback: '쉬웠어요',
    ingredientCount: '사용한 재료 개수 8개',
  },
  {
    id: 'r3',
    title: '계란 야채 볶음밥',
    time: '10분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 1,
    image: foodImage,
    isSaved: true,
    isCompleted: true,
    completedDate: '8월 15일 완료',
    feedback: '쉬웠어요',
    ingredientCount: '사용한 재료 개수 8개',
  },
  {
    id: 'r4',
    title: '고깃집 스타일 된장가득 술밥 찌개',
    time: '17분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 3,
    image: foodImage,
    isSaved: false,
    isCompleted: true,
    completedDate: '8월 15일 완료',
    feedback: '쉬웠어요',
    ingredientCount: '사용한 재료 개수 8개',
  },
  {
    id: 'r5',
    title: '계란 야채 볶음밥',
    time: '10분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 1,
    image: foodImage,
    isSaved: true,
    isCompleted: false,
  },
  {
    id: 'r6',
    title: '고깃집 스타일 된장 가..',
    time: '17분 소요',
    utilization: '재료 활용률 72%',
    difficulty: 3,
    image: foodImage,
    isSaved: false,
    isCompleted: false,
  },
];
