// 나중에 API로 교체할 더미 레시피 데이터
import foodImage from '../assets/mypage/recipe-food.png';

export const DUMMY_RECIPES = [
  {
    id: 'r1',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 구매 X',
    cost: '예상 재료비 1,800원',
    difficulty: 1,
    image: foodImage,
    isSaved: true,
    isCompleted: false,
  },
  {
    id: 'r2',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 2개',
    cost: '예상 재료비 1,800원',
    difficulty: 2,
    image: foodImage,
    isSaved: true,
    isCompleted: false,
  },
  {
    id: 'r3',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 구매 X',
    cost: '예상 재료비 1,800원',
    difficulty: 1,
    image: foodImage,
    isSaved: true,
    isCompleted: true,
  },
  {
    id: 'r4',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 2개',
    cost: '예상 재료비 1,800원',
    difficulty: 2,
    image: foodImage,
    isSaved: true,
    isCompleted: true,
  },
  {
    id: 'r5',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 구매 X',
    cost: '예상 재료비 1,800원',
    difficulty: 1,
    image: foodImage,
    isSaved: false,
    isCompleted: true,
  },
  {
    id: 'r6',
    title: '계란 야채 볶음밥',
    time: '15분 소요',
    extraIngredients: '추가 재료 2개',
    cost: '예상 재료비 1,800원',
    difficulty: 2,
    image: foodImage,
    isSaved: false,
    isCompleted: true,
  },
];
