import meatUrl from '@/assets/market/meatImg.png';
import squidUrl from '@/assets/market/squidImg.png';

export const products = [
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
  {
    id: 3,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 4,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
  {
    id: 5,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 6,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
];
export const productsDetail = [
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
    rank: '수산물 부문 1위',
    origin: '대한민국',
    review: 3281,
    isSave: true,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
    rank: '냉동식품 부문 2위',
    origin: '호주',
    review: 2503,
    isSave: false,
  },
  {
    id: 3,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
    rank: '수산물 부문 1위',
    origin: '대한민국',
    review: 3281,
    isSave: true,
  },
  {
    id: 4,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
    rank: '냉동식품 부문 2위',
    origin: '호주',
    review: 2503,
    isSave: false,
  },
  {
    id: 5,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
    rank: '수산물 부문 1위',
    origin: '대한민국',
    review: 3281,
    isSave: true,
  },
  {
    id: 6,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
    rank: '냉동식품 부문 2위',
    origin: '호주',
    review: 2503,
    isSave: false,
  },
];
export const timeSaleProduct = {
  id: 1,
  imgUrl: squidUrl,
  name: '손질 자숙 오징어 200g',
  price: 11570,
  discountRate: 30,
  discountPrice: 8900,
  targetDate: '2026-08-21T10:00:00',
};
export const saveRecipeProducts = [
  {
    id: 1,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 2,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
  {
    id: 3,
    imgUrl: squidUrl,
    name: '손질 자숙 오징어 200g',
    price: 11570,
    discountRate: 30,
    discountPrice: 8900,
  },
  {
    id: 4,
    imgUrl: meatUrl,
    name: '냉동 우삼겹 1kg ',
    price: 25900,
    discountRate: 5,
    discountPrice: 24500,
  },
];
export const recipes = [
  {
    imgUrl: meatUrl,
    name: '매콤 우삼겹 아끼소바',
  },
  {
    imgUrl: meatUrl,
    name: '우삼겹 부타동',
  },
  {
    imgUrl: meatUrl,
    name: '매콤 우삼겹 아끼소바',
  },
  {
    imgUrl: meatUrl,
    name: '우삼겹 부타동',
  },
];
